name: Pyzule

on:
  workflow_dispatch:
    inputs:
      repo_github:
        description: "Repository github: example: user/repository"
        default: "hiepvk/pyzu"
        required: true
        type: string
      ref_github:
        description: "Ref repository github: example: main, master, v.v"
        default: "main"
        required: true
        type: string
      ipa_url:
        description: "Direct URL to the decrypted App ipa."
        default: ""
        required: true
        type: string
      tweaks:
        description: "Folder deb, dylib, example: tweaks/xx.deb tw/xx.dylib"
        default: "tweaks/"
        required: true
        type: string
      ipa_name:
        description: "Modify the name of the app on the Home Screen."
        default: "NameApp"
        required: true
        type: string
      create_release:
        description: "Create a draft release"
        default: true
        required: false
        type: boolean
      upload_artifact:
        description: "Upload Artifact"
        default: true
        required: false
        type: boolean


jobs:
  build:
    name: Pyzule run
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4.1.1
        with:
          repository: ${{ inputs.repo_github }}
          ref: ${{ inputs.ref_github }}

      - name: Pyzule Install
        run: |
          mkdir ipa && mkdir build
          bash -c "$(curl https://raw.githubusercontent.com/asdfzxcvbn/pyzule/main/install-pyzule.sh)"

      - name: Download IPA
        id: download_ipa
        run: |
          wget "$IPA_URL" --no-verbose -O ipa/app.ipa
        env:
          IPA_URL: ${{ inputs.ipa_url }}

      - name: Inject
        run: |
          pyzule -i ipa/app.ipa -f ${{ inputs.tweaks }} -u -w -s -o build/${{ inputs.ipa_name }}.ipa

      - name: Upload a Build Artifact
        if: ${{ inputs.upload_artifact }}
        uses: actions/upload-artifact@v4.3.1
        with:
          name: ${{ inputs.ipa_name }}
          path: build/${{ inputs.ipa_name }}.ipa
          if-no-files-found: error

      - name: Create Release
        id: create_release
        uses: hiepvk/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT: ${{ inputs.create_release }}
        with:
          tag_name: ${{ inputs.ipa_name }}
          name: ${{ inputs.ipa_name }}
          files: build/${{ inputs.ipa_name }}.ipa
          draft: ${{ env.DRAFT }}
